pipeline {
	agent {
		label 'LM-AGENT'
	}
	options {
		timeout(time: 30, unit: 'Minutes')
	}
	stages {
		stage('git clone'){
			steps{
				sh 'date'
			}
		}
		stage('build') {
			steps{
				sh 'uptime'
			}
		}
		stage('Test') {
			steps{
				echo 'This is a Test stage'
			}
		}
		stage('deploy') {
			steps{
				echo 'this is a deploy stage'
			}
		}
	}
	post {
		always {
			echo 'job build'
		}
		success {
			echo 'job Success'
		}
		failure {
			echo 'job failed'
			deleteDir()
		}
	}
}