pipeline {
	agent {
		label 'LM-AGENT'
	}
	options {
		timeout(time: 30, unit: 'MINUTES')
		disableConcurrentBuilds()
	}
	environment {
		appVersion = '1.0.0'
		ACC_ID = '291293118913'
		PROJECT = "ISTHARA"
		COMPONENT = 'catalogue'
	}
	parameters{
		booleanParam(name: 'deploy', defaultValue: false, description: 'Toggle this value' )
	}
	stages {
		stage(env) {
			steps {
				sh """
					echo 'appVersion is ${appVersion}'
					echo 'ACC_ID is ${ACC_ID}'
				"""

			}
		}
		stage('git clone'){
			steps{
				sh 'date'
			}
		}
		stage('build') {
			steps{
				sh 'uptime'
			}
		}
		stage('Test') {
			steps{
				echo 'This is a Test stage'
			}
		}
		stage('deploy') {
			steps{
				echo 'this is a deploy stage'
			}
		}
	}
	post {
		always {
			echo 'job build'
		}
		success {
			echo 'job Success'
		}
		failure {
			echo 'job failed'
			deleteDir()
		}
	}
}