pipeline {
	agent any
	stages {
		stage('git clone'){
			steps{
				echo "this is a git clone stage"
			}
		}
		stage('build') {
			steps{
				echo 'This is a Build Stage'
			}
		}
		stage('Test') {
			steps{
				echo 'This is a Test stage'
			}
		}
		stage('deploy') {
			echo 'this is a deploy stage'
		}
	}
	post {
		always {
			echo 'job build'
		}
		success {
			echo 'job Success'
		}
		failure {
			echo 'job failed'
		}
	}
}