pipeline {
	agent {
        label 'pxt'
        disableConcurrentBuilds()
    }
    environment {
        appVesion = '1.0.0'
        region = 'u-east-1'
        project_id = 'isth' 
        component = 'dev'   
        }
    options{
        timeout(time: '30', units: 'MINUTES')
    }
	stages{
		stage('TEST'){
			steps{
				echo "This is a Jenkins Test Stage"
			}
		}
		stage('GIT CLONE') {
			steps{
				echo 'THIS is a GIT clone'
			}
		}
        stage('LINUX MULTI COMMANDS') {
            script {
                steps {
                    sh '''
                        uname -a
                        ls -l
                    '''    
                }
            }
        }
        stage('env'){
            script{
                steps{
                    echo '$env'
                }
            }
        }
	}
    post {
        always {
            echo "Build executed Successfully"
        }
        failure {
            echo "Build Failed"
        }
        success {
            echo "Build Success"
        }
    }


}