pipeline {
	agent {
        label 'pixxort'
    }
	stages{
		stage('TEST'){
			steps{
				echo "This is a Jenkins Test Stage"
			}
		}
		stage('GIT CLONE') {
			steps{
				echo 'THIS is a GIT clone'
			}
		}
	}

}

